# base_global_planner: global_planner/GlobalPlanner
planner_frequency: 2.0
controller_frequency: 5.0

# DWAPlannerROS:
#   max_vel_x: 1
#   min_vel_x: 0
#   max_vel_y: 1
#   min_vel_y: 0
#   max_rot_vel: 1.0
#   min_in_place_vel_theta: 0.4

#   acc_lim_theta: 3.2
#   acc_lim_x: 2.5
#   acc_lim_y: 2.5
