local_costmap:
  plugins: 
  - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation, type: "costmap_2d::InflationLayer"}
  # coordinate frame and tf parameters
  global_frame: /map
  robot_base_frame: base_link
  # rate parameters
  update_frequency: 5.0
  publish_frequency: 2.0

  # map managements parameters
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05

  #obstacles plugin
  obstacles:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: hokuyo_link, data_type: LaserScan, topic: /laser/scan, marking: true, clearing: true}
    obstacle_range: 5
    raytrace_range: 3.0

  # inflation
  inflation:
    inflation_radius: 1.5