local_costmap:
  # coordinate frame and tf parameters
  global_frame: /map
  robot_base_frame: base_link

  # rate parameters
  update_frequency: 5.0
  publish_frequency: 2.0

  # map managements parameters
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05

  # obstacles (costmap-2d/obstacles)
  obstacle_range: 5 # The maximum range in meters at which to insert obstacles into the costmap using sensor data
  raytrace_range: 3.0 # The maximum range in meters at which to raytrace out obstacles from the map using sensor data
  robot_radius: 0.5 # width = 360mm, length = 360mm, height = 95mm

  # inflation
  inflation_radius: 1.5
  cost_scaling_factor: 5.53

  # sensor management
  # inf_is_valid: true # Allows for Inf values in "LaserScan" observation messages. The Inf values are converted to the laser maximum range